language: go

notifications:
  email: false

go:
  - 1.13.x
  - master

before_install:
  - if [[ "$TRAVIS_GO_VERSION" == "1.13"* ]]; then go get github.com/mattn/goveralls; fi
script:
  - if [[ "$TRAVIS_GO_VERSION" == "1.13"* ]]; then $HOME/gopath/bin/goveralls -service=travis-ci --package="./..."; else go test ./...; fi
